version: "3.7"

services:
  workers:
    build: ./worker
    restart: always
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 1G
    networks:
      - bicyclenet
    volumes:
      - type: volume
        source: data
        target: /files

  storage:
    build: ./storage
    container_name: mrstorage
    volumes:
      - type: volume
        source: data
        target: /files

  rabbitmq:
    image: rabbitmq:3-alpine
    ports:
      - '5672:5672'
    networks:
      - bicyclenet

networks:
  bicyclenet:

volumes:
  data:
